apiVersion: v1
kind: Service
metadata:
  name: face-analyzer-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8585
      targetPort: 80
      protocol: TCP
  selector:
    app: face-analyzer
